---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangnan.
--- DateTime: 2025/4/8 17:08
---
--编写释放锁的脚本，让检验key和释放锁这两个操作实现原始性

--获取锁中的线程提示 get key
local id = redis.call('get', KEYS[1])
--比较线程标识与锁中的标识是否一致
if(id==ARGV[1]) then
    --释放锁 del key
    return redis.call('del', KEYS[1])
end
return 0


